### ISSUE TITLE
error deploying learn-chaincode to bluemix

### ISSUE THREAD

**Issue by learner4** [IBM-Blockchain/learn-chaincode#10]
I am getting following error deploying chaincode to bluemix (Deploy chaincode):
Any resolution or what am I doing wrong?
Following instruction from here :https://github.com/IBM-Blockchain/learn-chaincode#swagger-api
Registrar worked well, i get message user is logged in upon "GET" (i registered 2 users from user list)
However, deploying code failed with below message:

ERR - 15:51:29.908 [rest] ProcessChaincode -> INFO 0a1[0m REST sucessfully deploy chaincode: {"jsonrpc":"2.0","error":{"code":-32001,"message":"Deployment failure","data":"Error when deploying chaincode: Error getting chaincode package bytes: Error getting code process done with error = exit status 1"},"id":1}

**Comment by dshuffma-ibm** [comment]
Exit status 1 is usually when the chaincode is importing a shim that is incompatible with the hyperledger peer code. (though it could be caused by other things too)

So check these things:
- the `path` field in the deploy body is correct something like `"path": "https://github.com/ibm-blockchain/learn-chaincode/finished"`, if you have forked the repo then it would point to your URL and look similar.  It should point to the directory of the chaincode
- the import statement in your chaincode is using a **hyperledger** based shim (there is an older shim out there named **obc-peer** but its not supported by Bluemix IBM Blockchain networks)
```
import (
	"errors"
	"fmt"

	"github.com/hyperledger/fabric/core/chaincode/shim"
)
```

If all that checks out, could you reply back with the exact deploy body you are sending.

**Comment by learner4** [comment]
Yes, I forked it to my github account to tried to deploy the same finished code.

{
    "jsonrpc": "2.0",
    "method": "deploy",
    "params": {
        "type": 1,
        "chaincodeID": {
            "path": "https://github.com/sriefx143/learn-chaincode/tree/master/finished"
        },
        "ctorMsg": {
            "function": "init",
            "args": [
                "hi there"
            ]
        },
        "secureContext": "user_type1_xxxx"
    },
    "id": 1
}


import is from new version of shim interface "github.com/hyperledger/fabric/core/chaincode/shim"

user "GET" reply shows the user is logged in - 
{
"OK": "User user_type1_xxxx is already logged in."
}

can you please let me know where it is going wrong?

**Comment by dshuffma-ibm** [comment]
Your path is wrong.  Try this:

```
{
	"jsonrpc": "2.0",
	"method": "deploy",
	"params": {
		"type": 1,
		"chaincodeID": {
			"path": "https://github.com/sriefx143/learn-chaincode/finished"
		},
		"ctorMsg": {
			"function": "init",
			"args": [
				"hi there"
			]
		},
		"secureContext": "user_type1_xxxx"
	},
	"id": 1
}
```

Notice how my path field above does not have `tree/master` in it.  This is becaue the path field is a `go get <url>`. It is not the same url you would use in your browser for github.

**Comment by learner4** [comment]
that was silly..got it and works! thank you
