### ISSUE TITLE
how can i set the invoke response message when i use restful api

### ISSUE THREAD

**Issue by t2krew** [IBM-Blockchain/learn-chaincode#145]
```json
{
  "jsonrpc": "2.0",
  "result": {
    "status": "OK",
    "message": "b3cb98cc-ac00-4ef4-9a90-76445d3e2cab"
  },
  "id": 5
}
```

i want to return something special to the result message, but always get the random string likes "b3cb98cc-ac00-4ef4-9a90-76445d3e2cab".

**Comment by masterDev1985** [comment]
@t2krew you cannot set the response message.  This is because the transaction is not actually processed within the scope of the invoke call.  All the peer can really tell you at that point is that the transaction will have the given ID after it has been processed and added to a block.  You're probably looking to modify the message so that you can check whether a transaction was successful or not.  You should use queries to perform these checks.

I'll go ahead and close this issue, but I hope some of that helps!

**Comment by t2krew** [comment]
@masterDev1985  thx
